### ISSUE TITLE
static compilation of jade to html

### ISSUE THREAD

**Issue by ghost** [icflorescu/aspa#2]
hi,
  with few change, i was able to handle entry like this:

index.html:
  from:
      src/index.jade  : { }

 I'm yet to make this to a proper patch.
  Will you be interested in covering this use case ?
-Vardhan

**Comment by icflorescu** [comment]
Interesting idea. I'm not sure I see the generic use case... although... if implemented correctly, then one could use [aspa](https://github.com/icflorescu/aspa) to fully build & "package" a static website that can be deployed anywhere. Am I right, is that what you're thinking?

If you can post a [gist](https://gist.github.com/) with your changes (or otherwise ellaborate a bit on the idea), I'll definitely have a look at it and see how we could turn it into a feature.

There's also the problem of adjusting file references - for instance, if you have a ref to `fonts/fontello.svg` in one of your styling files, after compression and fingerprinting, in _production mode_ it will become something like `fonts/1361917868718.fontello.svg.gz` (see [this](https://github.com/icflorescu/aspa/blob/master/lib/aspa.iced#L28-L70) and [this](https://github.com/icflorescu/aspa/blob/master/lib/aspa.iced#L117-L124) code).
I have a feeling that implementing this kind of functionality for assets referred from an HTML file (like scripts, images, ...) could complicate things a bit...

**Comment by ghost** [comment]
Yes, I'm looking for static site generation, but something which is bare-bone ...  not a full stack like  docpad (-:
Since i hadn't handled the the uniqification, my patch isn't ready. What i have  is really
simple .. just calling compile instead of copy for html output extension, and evaluating the
 return function of jade.compile().

BTW, have you looked at the transformers package : https://github.com/ForbesLindesay/transformers ?

-Vardhan

**Comment by icflorescu** [comment]
[Transformers](https://github.com/ForbesLindesay/transformers) looks interesting indeed (apparently it can handle almost averything you throw at it :-), though a bit too abstract for my needs...

Would be even nicer if somebody would "package" it into a ready to use folder-watching command line utility.

Actually that was the basic idea behind [aspa](https://github.com/icflorescu/aspa) - sometimes people have "practical concerns" related to small or medium sized projects, since not every project out there has the complexity of Facebook or Klout, and not everybody uses complex building tools like jake, grunt, brewer, yeoman, etc.

I also drew some inspiration from [flour](http://ricardo.cc/cake-flour/) (you might want to check that one too), but it didn't have compression and fingerprinting...

Regarding the issue at hand, if you believe there's enough of an user base for this usage scenario, please feel free to do a fork & pull request if / whenever you have the time.

**Comment by ghost** [comment]
Somehow my text while closing got lost.
I figured out that command line jade can do inclusions and conversions using filter  & transformers !
So if i put 'include app.coffee' or 'include style.styl'   the result is js being inserted in the final html with proper script/style  tags !
Right now, this is working perfectly fine for me .

I completely agree with your explanation about need of aspa.
BTW .. i also find this unix utility called inotifywait, which can detect a change in file status, and rerun jade ... needed when included files are updated with command line jade ....

**Comment by icflorescu** [comment]
No problem, and thanks for sharing your thoughts!

It's good to know about the command line jade options. I'll definitely keep that in mind, especially since lately I've been using jade & slim (for Ruby) so much that I got used to it and now I find writing in plain old HTML too cumbersome and last-centurish :-)...
